config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/new'
  get 'bookmarks/create'
  get 'bookmarks/destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "categories#index"
  # resources :categories, only: [:index, :show, :new]
  resources :categories, except: [ :edit, :update, :destroy ] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :recipe
  belongs_to :category
  validates :recipe_id, uniqueness: { scope: :category_id }
  validates :comment, length: { minimum: 6 }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :recipes, through: :bookmarks
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :bookmarks
  validates :description, presence: true
  validates :name, presence: true, uniqueness: true
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @bookmark = Bookmark.new
    @recipes = Recipe.all - @category.recipes

  end

  def create
    @category = Category.find(params[:category_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.category = @category
    if @bookmark.save
      redirect_to category_path(@category)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to category_path(@bookmark.category)
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :recipe_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new

  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to category_path(@category)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/new.html.erb
<div class="form-container">
  <h2>add a recipe to <%= @category.name %> category</h2>

  <%= simple_form_for [@category, @bookmark], html: { multipart: true } do |f| %>
    <%= f.input :comment%>
    <%= f.association :recipe %>

    <%= f.button :submit, "Add recipe", class: "btn-submit" %>
  <% end %>
</div>

app/views/categories/index.html.erb
<div class="banner" style="background-image: url('<%= image_path("banner.jpg") %>')">
  <div class="headings">
    <h1>CookBook</h1>
    <h3>Save your favourites recipes</h3>
  </div>
</div>

<div class="container w-75">
  <div class="info-top">
    <h2>List of Categories</h2>
    <%= link_to 'New category', new_category_path, class: "btn btn-warning" %>
  </div>


  <div class="cards">
    <% @categories.each do |category| %>
      <%= link_to category_path(category) do %>
        <% if category.photo.attached? %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path(category.photo.key) %>')">
          <div>
            <h3><%= category.name %></h3>
            <p><%= category.bookmarks.count %> recipes</p>
          </div>
        </div>
        <% else %>
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg')">
          <div>
            <h3><%= category.name %></h3>
            <p><%= category.bookmarks.count %> recipes</p>
          </div>
        </div>

        <% end %>
      <% end %>

    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="form-container">
  <h2>Add a new Category</h2>

  <%= simple_form_for @category, html: { multipart: true } do |f| %>
    <%= f.input :name, placeholder: "The category name.." %>

    <%= f.input :photo, as: :file, label: "Photo" %>

    <%= f.button :submit, "Create Category", class: "btn-submit" %>
  <% end %>
</div>

app/views/categories/show.html.erb
<% if @category.photo.attached? %>
    <div class="banner" style="background-image: url('<%= cl_image_path(@category.photo.key)%>')">
      <div>
        <h1><%= @category.name %></h1>
      </div>
  </div>
<% else %>
  <div class="banner" style="background-image: url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
    <div>
      <h1><%= @category.name %></h1>
    </div>
  </div>
<% end %>



<div class="container w-75">

    <div class="info-top">
        <h2>Recipes</h2>
        <%= link_to 'Add a Recipe', new_category_bookmark_path(@category), class:"btn btn-warning" %>
    </div>

    <div class="cards">
      <% @category.bookmarks.each do |bookmark| %>
      <div class="card-trip">
        <img src = "<%= bookmark.recipe.image_url %>">
        <%= link_to bookmark_path(bookmark),
            data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
            class: 'btn-delete' do %>
            <i class="fa-solid fa-trash"></i>
         <% end %>

        <div class="card-trip-description">
          <h3><%= bookmark.recipe.name %></h3>
          <p><%= bookmark.recipe.description.truncate(100) %></p>
        </div>

        <div class="card-trip-infos">
          <div>
            <p><%= bookmark.comment %></p>
          </div>
          <div>
            <%= bookmark.recipe.rating %> <%= '⭐' * bookmark.recipe.rating.floor %>
          </div>


        </div>
      </div>
      <% end %>

    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCookbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "/shared/navbar" %>
    <%= yield %>
</html>
  </body>

app/views/shared/_navbar.html.erb
<div class="navbar mt-6">
  <%= image_tag 'logo1.png' %>
  <div class= "navbar_links">
    <%= link_to 'Home', root_path %>
    <%= link_to 'New Category', new_category_path %>
  </div>

</div>